#!/usr/bin/perl
use v5.38;

use lib qw(lib);

our $VERSION = '0.010';

use eBird::CLI;
my $cli = eBird::CLI->new;

push @ARGV, 'help' unless @ARGV;
$cli->run( @ARGV );

=head1 NAME

ebird - command line interface to eBird

=head1 SYNOPSIS

	ebird login

	ebird checklist list
	ebird checklist list --mine

	ebird checklist list --top100 [region]

	ebird checklist fetch ABCDEDFG

	ebird locale list

	ebird track ABCDEDFG

	ebird region list
	ebird region list REGION


	ebird

=head1 DESCRIPTION

=cut


